galaxy_info:
  role_name: promtail
  namespace: mjay_kerberos
  author: Juliet Meza
  description: A role to install and configure Loki log aggregator.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - loki
    - logging
