- name: Install Loki
  vars:
    loki_version: 2.7.4
    loki_os: linux
    loki_arch: amd64
    loki_binary_name: "loki-{{ loki_version }}.{{ loki_os }}-{{ loki_arch }}.tar.gz"
    loki_binary_url: "{{ loki_base_url }}/{{ loki_version }}/{{ loki_binary_name }}"
    loki_extracted_dir_name: "loki-{{ loki_version }}.{{ loki_os }}-{{ loki_arch }}"
  get_url:
    url: "{{ loki_binary_url }}"
    dest: "/tmp/{{ loki_binary_name }}"
    mode: '0644'
  become: true
  tags: [loki]

- name: Extract Loki
  vars:
    loki_install_dir: /usr/local/bin
  unarchive:
    src: "/tmp/{{ loki_binary_name }}"
    dest: "{{ loki_install_dir }}"
    remote_src: true
    copy: false
  become: true
  tags: [loki]

- name: Configure Loki
  vars:
    loki_config_path: /etc/loki-config.yaml
  template:
    src: loki-config.yaml.j2
    dest: "{{ loki_config_path }}"
  become: true
  tags: [loki]

- name: Create Loki Systemd Service
  vars:
    loki_systemd_path: /etc/systemd/system/loki.service
  template:
    src: loki.service.j2
    dest: "{{ loki_systemd_path }}"
  become: true
  tags: [loki]

- name: Enable and Start Loki Systemd Service
  systemd:
    name: loki
    enabled: true
    state: started
  become: true
  tags: [loki]
