- name: Install Loki
  vars:
    src: "../defaults/main.yml"
  ansible.builtin.get_url:
    url: "{{ loki_binary_url }}"
    dest: "/tmp/{{ loki_binary_name }}"
    mode: '0644'
  become: true
  tags: [loki]

- name: Extract Loki
  vars:
    loki_install_dir: "../defaults/main.yml"
  unarchive:
    src: "/tmp/{{ loki_binary_name }}"
    dest: "{{ loki_install_dir }}"
    remote_src: true
    copy: false
  become: true
  tags: [loki]

- name: Configure Loki
  vars:
    loki_config_path: /etc/loki-config.yaml
  template:
    src: loki-config.yaml.j2
    dest: "{{ loki_config_path }}"
  become: true
  tags: [loki]

- name: Create Loki Systemd Service
  vars:
    loki_systemd_path: /etc/systemd/system/loki.service
  template:
    src: loki.service.j2
    dest: "{{ loki_systemd_path }}"
  become: true
  tags: [loki]

- name: Create Loki directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ loki_config_dir }}"
    - "{{ loki_data_dir }}"

- name: Set Loki directory permissions
  file:
    path: "{{ item }}"
    mode: "0755"
  loop:
    - "{{ loki_config_dir }}"
    - "{{ loki_data_dir }}"

- name: Enable and Start Loki Systemd Service
  systemd:
    name: loki
    enabled: true
    state: started
  become: true
  tags: [loki]
