# Copies a compiled version of prometheus-slurm-exporter and installs onto the specified inventory.
# Creates a systemd file for starting, without actually using systemd. Design
# decision was made to not use systemd for use with images
---
- name: Create nodeusr account to run the slurm exporter
  ansible.builtin.user:
    name: nodeusr
    shell: /sbin/nologin
    home: /var/lib/node_exporter
    uid: "{{ prometheus_exporter_uid }}"
  tags:
    - slurm_exporter

- name: Copy over the compiled slurm exporter
  ansible.builtin.copy:
    src: prometheus-slurm-exporter 
    dest: "/var/lib/node_exporter/"
    owner: nodeusr
    group: nodeusr
    remote_src: no
    mode: 0755
  tags:
    - slurm_exporter

- name: Create systemd service file
  ansible.builtin.template:
    src: slurm_exporter.service.j2
    dest: /etc/systemd/system/slurm_exporter.service
  tags:
    - slurm_exporter

- name: Enable the systemd service file manually
  ansible.builtin.file:
    state: link
    src: /etc/systemd/system/slurm_exporter.service
    dest: /etc/systemd/system/multi-user.target.wants/slurm_exporter.service
  tags:
    - slurm_exporter

- name: Start the systemd service file if this is not a chroot
  ansible.builtin.service:
    name: slurm_exporter
    state: started
  when: not ansible_is_chroot
  tags:
    - slurm_exporter
