# defaults file for promtail

# The version of Promtail to install
promtail_version: 2.7.4

# The base URL for downloading the Promtail binary
promtail_base_url: https://github.com/grafana/loki/releases/download

# The architecture of the system
promtail_arch: "amd64"

# The operating system of the system
promtail_os: "linux"

# The location to install the Promtail binary
promtail_install_dir: /usr/local/bin

# The name of the Promtail binary
promtail_binary_name: "promtail-{{ promtail_version }}.{{ promtail_os }}-{{ promtail_arch }}.zip"

# The location of the Promtail configuration file
promtail_config_file: /etc/promtail/config.yaml

# The user under which Promtail will be run
promtail_user: promtail

# The group under which Promtail will be run
promtail_group: promtail
