---
- name: Gather os specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family }}.yaml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}\
           .yaml"
      paths:
        - "{{ role_path }}/vars"
  tags:
    - spack
  when: spack_root_host | bool

- name: Install required packages
  ansible.builtin.package:
    name: "{{item}}"
    state: present
  when: spack_root_host | bool
  loop: "{{spack_required_packages}}"
  tags:
    - spack

- name: Set git config for manyFiles
  git_config:
    name: feature.manyFiles
    scope: global
    value: "true"
  when: spack_root_host | bool
  tags:
    - spack

- name: clone spack repository
  git:
    repo: "{{spack_repo}}"
    dest: "{{spack_root}}"
    version: "{{spack_version}}"
  when: spack_root_host | bool
  tags:
    - spack

- name: Copy spack sh config
  template:  
    src: templates/zz-spack.sh
    dest: /etc/profile.d/zz-spack.sh
  tags:
    - spack

- name: copy spack csh config
  template:  
    src: templates/zz-spack.csh
    dest: /etc/profile.d/zz-spack.csh
  tags:
    - spack

- name: enable lmod bash
  lineinfile:
    path: /etc/sysconfig/modules/lmod/cm-lmod-init.sh
    regexp: ENABLE_LMOD
    line: "export ENABLE_LMOD=1"
  when: spack_bright
  tags:
    - spack

- name: enable lmod csh
  lineinfile:
    path: /etc/sysconfig/modules/lmod/cm-lmod-init.csh
    regexp: ENABLE_LMOD
    line: 'setenv ENABLE_LMOD "1"'
  when: spack_bright
  tags:
    - spack

- name: Copy spack configuration file
  ansible.builtin.copy:
    content: |
      config:
        {{ spack_config_config_yaml | to_nice_yaml(indent=2, sort_keys=False) | indent(2,false) }}
    dest: "{{spack_root}}/etc/spack/config.yaml"
    backup: yes
    force: true
  when:
    - spack_root_host | bool
    - spack_config_config_yaml
  tags:
    - spack

- name: Copy spack module configuration file
  ansible.builtin.copy:
    content: |
      modules:
        {{ spack_config_modules_yaml | to_nice_yaml(indent=2, sort_keys=False) | indent(2,false) }}
    dest: "{{spack_root}}/etc/spack/modules.yaml"
    backup: yes
    force: true
  when: 
    - spack_root_host | bool
    - spack_config_modules_yaml
  tags:
    - spack

- name: Copy spack package configuration file
  ansible.builtin.copy:
    content: |
      packages:
        {{ spack_config_packages_yaml | to_nice_yaml(indent=2, sort_keys=False) | indent(2,false) }}
    dest: "{{spack_root}}/etc/spack/packages.yaml"
    force: true
  when:
    - spack_root_host | bool
    - spack_config_packages_yaml
  tags:
    - spack
