---
- name: Gather os specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family }}.yaml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}\
           .yaml"
      paths:
        - "{{ role_path }}/vars"
  tags:
    - spack
  when: spack_root_host | bool

- name: Install required packages
  ansible.builtin.package:
    name: "{{item}}"
    state: present
  when: spack_root_host | bool
  loop: "{{spack_required_packages}}"
  tags:
    - spack

- name: clone spack repository
  git:
    repo: "{{spack_repo}}"
    dest: "{{spack_root}}"
    version: "{{spack_version}}"
    depth: 1
    single_branch: yes
    version: develop
  when: spack_root_host | bool
  tags:
    - spack

- name: Copy spack sh config
  template:  
    src: templates/zz-spack.sh
    dest: /etc/profile.d/zz-spack.sh
  tags:
    - spack

- name: copy spack csh config
  template:  
    src: templates/zz-spack.csh
    dest: /etc/profile.d/zz-spack.csh
  tags:
    - spack

- name: enable lmod bash
  lineinfile:
    path: /etc/sysconfig/modules/lmod/cm-lmod-init.sh
    regexp: ENABLE_LMOD
    line: "export ENABLE_LMOD=1"
  when: spack_bright
  tags:
    - spack

- name: enable lmod csh
  lineinfile:
    path: /etc/sysconfig/modules/lmod/cm-lmod-init.csh
    regexp: ENABLE_LMOD
    line: 'setenv ENABLE_LMOD "1"'
  when: spack_bright
  tags:
    - spack

- name: Copy spack configuration file
  template:
    src: templates/config.yaml
    dest: "{{spack_root}}/etc/spack/config.yaml"
    backup: yes
    force: no
  when: spack_root_host | bool
  tags:
    - spack

- name: Copy spack module configuration file
  ansible.builtin.template:
    src: files/modules.yaml.j2
    dest: "{{spack_root}}/etc/spack/modules.yaml"
    backup: yes
    force: no
  when: spack_root_host | bool
  tags:
    - spack

- name: Copy spack package configuration file
  copy:
    src: files/packages.yaml
    dest: "{{spack_root}}/etc/spack/packages.yaml"
    force: no
  when: spack_root_host | bool
  tags:
    - spack
