- name: Create Loki directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ loki_config_dir }}"
    - "{{ loki_data_dir }}"

- name: Set Loki directory permissions
  file:
    path: "{{ item }}"
    mode: "0755"
  loop:
    - "{{ loki_config_dir }}"
    - "{{ loki_data_dir }}"
