---
# tasks file for x2go-server
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yaml"
        - "{{ ansible_distribution }}.yaml"
        - "{{ ansible_distribution_file_variety }}.yaml"
      paths:
        - '{{role_path}}/vars'
  tags:
    - x2goserver

- name: Install epel for RHEL
  when: ansible_distribution_file_variety == 'RedHat'
  ansible.builtin.package:
    name: "epel-release"
    state: present
  tags:
    - x2goserver

- name: Install packages
  ansible.builtin.dnf:
    name: "{{item}}"
    state: present
    enablerepo: powertools
  loop: "{{x2goserver_packages}}"
  tags:
    - x2goserver

- name: Disable compositing
  ansible.builtin.lineinfile:
    path: /usr/share/xfwm4/defaults
    regexp: "^use_compositing="
    line: "use_compositing=false"
    backup: true
  tags:
    - x2goserver

- include: debian.yaml
  when: ansible_distribution == 'Debian'
  tags:
    - x2goserver
