---  
- name: Gather os specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family }}.yaml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}\
           .yaml"
      paths:
        - "{{ role_path }}/vars"
  tags:
    - clustershell

- name: Install required packages
  ansible.builtin.package:
    name: "{{item}}"
    state: present
  loop: "{{clustershell_required_packages}}"
  tags:
    - clustershell


#Copy out template file that uses SLURM for groups
- name: Copy template file
  ansible.builtin.template:
    src:  templates/groups.conf.j2 
    dest: /etc/clustershell/groups.conf
    owner: root
    group: root
    mode: 644
  tags:
    - clustershell

- name: Copy sudo mode config file
  ansible.builtin.template:
    src: templates/sudo.conf.j2
    dest: /etc/clustershell/clush.conf.d/sudo.conf
    owner: root
    group: root
    mode: 644
  tags:
    - clustershell

- name: Copy cluster config file
  ansible.builtin.template:
    src: templates/cluster.yaml.j2
    dest: /etc/clustershell/groups.d/cluster.yaml
    owner: root
    group: root
    mode: 644
  tags:
    - clustershell
