---  
- name: Install/update epel repository if needed
  ansible.builtin.package:
    name: epel-release
    state: present
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '7'
  tags:
    - clustershell      
    
# tasks file for clustershell
# because this is a cluster utility tool, we will install to /etc with yum
- name: Install clustershell
  ansible.builtin.package:
    name: clustershell
    state: present
  tags:
    - clustershell

#Copy out template file that uses SLURM for groups
- name: Copy template file
  ansible.builtin.template:
  src:  templates/groups.conf.j2 
  dest: /etc/clustershell/groups.conf
  owner: root
  group: root
  mode: 644
