#!/usr/bin/python3
# Replaces GPU BusIDs in /etc/X11/xorg.conf on each boot
import subprocess as sp

def gather_busids():
    """
        Gathers GPU BusID values using nvidia-xconfig tool and formats into a string based list
    """
    output = sp.check_output("nvidia-xconfig --query-gpu-info | grep -i BusID | cut -d ' ' -f6", shell=True).decode("utf-8").splitlines()
    return output

def replace_xorg_entries(path='/etc/X11/xorg.conf'):
    """
        Takes the gathered BusID values and replaces the ones present in xorg.conf with them
    """
    with open(path, 'r') as fileptr:
        contents = fileptr.readlines()

    bus_id = 0
    busids = gather_busids()
    for i, line in enumerate(contents):
      if 'BusID' in line:
        contents[i] = f"    BusID          \"{busids[bus_id]}\" # Generated by boot script\n"
        bus_id += 1

    with open(path, 'w') as fileptr:
        fileptr.writelines(contents)

replace_xorg_entries()
