---
- name: Gather os specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family }}.yaml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version}}.yaml"
      paths:
        - "{{ role_path }}/vars"
  tags:
    - mounts

- name: Install Relevant packages packages
  vars:
  ansible.builtin.package: 
    name: "{{item}}"
    state: present
  loop:
    - "{{ mounts_required_packages }}"
  tags:
    - mounts

- name: create mount directory
  ansible.builtin.file:
    state: directory
    path: "{{mount.path}}"
  tags:
    - mounts

- name: format filesystem
  community.general.filesystem:
    fstype: "{{mount.fstype}}"
    dev: "{{mount.src}}"
    state: "present"
  when: mount.mkfs
  tags:
    - mounts

- name: Mount
  ansible.posix.mount:
    path: "{{mount.path}}"
    state: mounted
    fstype: "{{mount.fstype}}"
    opts: "{{mount.opts}}"
    src: "{{mount.src}}"
  tags:
    - mounts

