---
# tasks file for cronjobs
- name: "Create cronjobs name {{cronjob_cron_name}}"
  community.healthchecksio.checks:
    state: present
    api_key: "{{ cronjob_healthcheck_project_api_key }}"
    name: "{{cronjob_cron_name}}"
    unique: ["name"]
    channels: "*"
    grace: "{{cronjob_grace}}"
    tags: "{{cronjob_tags}}"
    desc: "{{cronjob_description}}"
    schedule: "{{cronjob_schedule}}"
    tz: "{{cronjob_tz}}"
  register: output
  tags:
    - always

- name: Create cronjob
  ansible.builtin.cron:
    name: "{{cronjob_cron_name}}"
    minute: "{{cronjob_minute}}"
    hour: "{{cronjob_hour}}"
    day: "{{cronjob_day}}"
    month: "{{cronjob_month}}"
    weekday: "{{cronjob_weekday}}"
    job: "{{cronjob_job}} && curl -fsS -m 10 --retry 5 -o /dev/null {{cronjob_healthcheck_url}}/ping/{{output.uuid}}"
  tags:
    - always
