---
- name: restart prometheus
  service: name=prometheus state=restarted
  when: not ansible_is_chroot

- name: reload prometheus
  service: name=prometheus state=reloaded
  when: not ansible_is_chroot

- name: stop prometheus
  service: name=prometheus state=stopped
  when: not ansible_is_chroot


- name: restart node_exporter
  service: name=node_exporter state=restarted
  when: not ansible_is_chroot

- name: reload node_exporter
  service: name=node_exporter state=reloaded
  when: not ansible_is_chroot

- name: stop node_exporter
  service: name=node_exporter state=stopped
  when: not ansible_is_chroot


- name: restart alertmanager
  service: name=alertmanager state=restarted
  when: not ansible_is_chroot

- name: reload alertmanager
  service: name=alertmanager state=reloaded
  when: not ansible_is_chroot

- name: stop alertmanager
  service: name=alertmanager state=stopped
  when: not ansible_is_chroot
