---
- name: restart prometheus
  service: name=prometheus state=restarted

- name: reload prometheus
  service: name=prometheus state=reloaded

- name: stop prometheus
  service: name=prometheus state=stopped


- name: restart node_exporter
  service: name=node_exporter state=restarted

- name: reload node_exporter
  service: name=node_exporter state=reloaded

- name: stop node_exporter
  service: name=node_exporter state=stopped


- name: restart alertmanager
  service: name=alertmanager state=restarted

- name: reload alertmanager
  service: name=alertmanager state=reloaded

- name: stop alertmanager
  service: name=alertmanager state=stopped
