smartmon: https://github.com/janw/node-exporter-textfile-collector-scripts/raw/master/smartmon.sh
node_exporter_link: https://github.com/prometheus/node_exporter/releases/download/
node_exporter_version: 1.3.1
uid: 440
