---
# tasks file for metabase
- name: create metabase data diretory
  file:
    path: "{{metabase_data_dir}}"
    owner: root
    group: root
    state: directory
  tags:
    - metabase

- name: Set labels
  ansible.builtin.set_fact:
    metabase_docker_labels: 
      traefik.enable: "true"
      traefik.http.routers.metabase.entrypoints: "websecure"
      traefik.http.routers.metabase.rule: "Host(`{{metabase_site_root}}`)"
      traefik.http.routers.metabase.tls: "true"
      traefik.http.routers.metabase.tls.certresolver: letsencrypt
      traefik.http.services.metabase.loadbalancer.server.port: "3000"
      traefik.docker.network: traefik_proxy
    metabase_docker_networks:
      - name: traefik_proxy
  when: metabase_traefik_enable
  tags:
    - metabase

- name: Start docker container
  community.docker.docker_container:
    name: metabase
    image: "metabase/metabase:{{metabase_image_version}}"
    state: started
    restart_policy: always
    volumes:
      - "{{metabase_data_dir}}:/metabase-data"
    labels: "{{metabase_docker_labels}}"
    networks: "{{metabase_docker_networks}}"
    env:
      MB_DB_FILE: /metabase-data/metabase.db
    log_options:
      max-size: "10m"
      max-files: "3"
  tags:
    - metabase


