---
- name: Converge
  hosts: all
  tasks:
    - name: Install sudo
      ansible.builtin.package:
        name: sudo
        state: present
    - name: "Include cgroups exporter server"
      ansible.builtin.include_role:
        name: "cgroups_exporter"
