---
# tasks file for restic
- name: install restic
  package:
    name: restic
    state: present
  tags:
    - restic

- name: create password file
  template:
    src: templates/password_file.j2
    dest: "{{restic_password_file_path}}"
    owner: root
    group: root
  tags:
    - restic

- name: create drestic wrapper
  template:
    src: templates/drestic.j2
    dest: /usr/local/sbin/drestic
    owner: root
    group: root
    mode: "0500"
  tags:
    - restic

- name: Check to initialize restic
  shell: "/usr/local/sbin/drestic snapshots || /usr/local/sbin/drestic init"
  tags:
    - restic
