---
- name: Create nodeusr account to run gpfs_exporter
  user:
    name: nodeusr
    shell: /sbin/nologin
    home: /var/lib/node_exporter
    uid: "{{ prometheus_exporter_uid }}"

- name: Extract gpfs_exporter downloaded tarball
  unarchive:
    src: "https://github.com/treydock/gpfs_exporter/releases/download/v{{ gpfs_exporter_version }}/gpfs_exporter-{{ gpfs_exporter_version }}.linux-amd64.tar.gz"
    dest: "{{ gpfs_exporter_executable_path }}"
    owner: nodeusr
    group: nodeusr
    mode: 0755
    remote_src: yes

- name: Create systemd service file
  template:
    src: gpfs_exporter.service.j2
    dest: /etc/systemd/system/gpfs_exporter.service

- name: Enable the systemd service file manually
  file:
    state: link
    src: /etc/systemd/system/gpfs_exporter.service
    dest: /etc/systemd/system/multi-user.target.wants/gpfs_exporter.service

- name: Start the systemd service file if this is not a chroot
  service:
    name: gpfs_exporter
    state: started
  when: ansible_is_chroot == False

- name: Set cronjob for gpfs_mmdf_exporter
  cron:
    name: "run gpfs_mmdf_exporter to node_exporter collector"
    hour: "*/4"
    job: "gpfs_mmdf_exporter --collector.mmdf.timeout=600  --output /var/lib/node_exporter/textfile_collector/gpfs_mmdf_exporter.prom 2>&1"
  tags:
    - gpfs_mmdf_exporter
    - never