---
# tasks file for fail2ban
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yaml"
        - "{{ ansible_distribution }}.yaml"
        - "{{ ansible_distribution_file_variety }}.yaml"
      paths:
        - '{{role_path}}/vars'
  tags:
    - fail2ban

- name: Install fail2ban centos
  package:
    name: "{{item}}"
    state: present
  tags:
    - fail2ban
  loop: "{{fail2ban_packages}}"

- name: enable and start fail2ban service
  service:
    name: fail2ban
    state: started
    enabled: yes
  tags:
    - fail2ban

- name: copy action.d files
  copy:
    src: templates/iptables-common.local.j2
    dest: "{{fail2ban_data_dir}}/action.d/iptables-common.local"
    owner: root
    group: root
  notify: 
    - restart fail2ban
  tags:
    - fail2ban

- name: copy action.d files
  template:
    src: templates/jail.d/jail.local.j2
    dest: "{{fail2ban_data_dir}}/jail.d/jail.local"
    owner: root
    group: root
  notify: 
    - restart fail2ban
  tags:
    - fail2ban


- name: copy bitwarden template files
  template:
    src: "templates/{{item}}.j2"
    dest: "{{fail2ban_data_dir}}/{{item}}"
    owner: root
    group: root
  notify: 
    - restart fail2ban
  when: fail2ban_vaultwarden_log_path
  loop:
    - filter.d/bitwarden-admin.local
    - filter.d/bitwarden.local
    - jail.d/bitwarden-admin.local
    - jail.d/bitwarden.local
  tags:
    - fail2ban

