---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-el8
    image: rockylinux:8
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    pre_build_image: true
    command: "/usr/sbin/init"
    cgroupns_mode: host

provisioner:
  name: ansible
verifier:
  name: ansible
