---
# tasks file for dst
# TODO: Always runs a repo/apt update at the beginning, if it hasn't been run in a while

- name: Update apt cache if out of date
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_distribution == 'Debian'
  tags:
    - common

- name: create hpcadmin group
  ansible.builtin.group:
    name: hpcadmin
    state: present
  tags:
    - common

- name: create dst user
  ansible.builtin.user:
    name: dst
    password: "{{ common_dst_user_password }}"
    groups:
      - hpcadmin
    state: present
    shell: /bin/bash
    createhome: yes
    home: "{{common_dst_user_home}}"
    uid: "{{common_dst_user_uid}}"
  tags:
    - common

# Needs to be configured after setting the password for the user
- name: Allow 'hpcadmin' group to have password sudo
  lineinfile:
    dest: /etc/sudoers.d/hpcadmin
    create: yes
    state: present
    regexp: '^%hpcadmin'
    line: '%hpcadmin ALL=(ALL) PASSWD: ALL'
    validate: visudo -cf %s
  tags:
    - common

- name: Add dst user authorized_key
  ansible.posix.authorized_key:
    user: "dst"
    state: present
    key: "{{common_dst_authorized_key}}"
  tags:
    - common

- name: Add dst user private_key
  ansible.builtin.copy:
    content: "{{common_dst_private_key}}"
    dest: "{{common_dst_user_home}}/.ssh/id_rsa"
    owner: "dst"
    group: "dst"
    mode: "0600"
  tags:
    - common

- name: create users
  ansible.builtin.user:
    name: "{{item.name}}"
    state: "{{item.state|default('present')}}"
    password: "{{item.password}}"
    groups:
      - hpcadmin
    createhome: yes
    expires: -1
    uid: "{{item.uid}}"
  loop: "{{common_dst_users}}"
  tags:
    - common

- name: Add entries to ssh configs
  ansible.posix.authorized_key:
    user: "{{item.name}}"
    state: present
    key: "{{item.authorized_key}}"
  loop: "{{common_dst_users}}"
  tags:
    - common

- name: Set system hostname
  ansible.builtin.hostname:
    name: "{{common_hostname}}"
    use: '{{hostname_use}}'
  when: common_hostname
  tags:
    - common

# Avoids some sudo warning when changing the hostname
- name: Set system hostname in etc hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 {{common_hostname}}"
    insertbefore: "127.0.0.1 localhost"
  when: common_hostname
  tags:
    - common

- name: Set timezone
  community.general.timezone:
    name: "{{common_timezone}}"
  tags:
    - common

- name: Add additional hostnames
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    create: yes
    state: present
    line: '{{item}}'
    backup: yes
  loop: "{{common_additional_etc_hosts}}"
  tags:
    - common
