---
# tasks file for dst
- name: Allow 'hpcadmin' group to have password sudo
  lineinfile:
    dest: /etc/sudoers.d/hpcadmin
    create: yes
    state: present
    regexp: '^%hpcadmin'
    line: '%hpcadmin ALL=(ALL) PASSWD: ALL'
    validate: visudo -cf %s

- name: create hpcadmin group
  group:
    name: hpcadmin
    state: present

- name: create dst user
  user:
    name: dst
    password: "{{common_dst_user_password}}"
    groups:
      - hpcadmin
    state: present
    shell: /bin/bash
    createhome: yes
    home: /usr/local/dst
    uid: "{{common_dst_user_uid}}"
