---
# tasks file for firezone
- name: install required packages
  package:
    name: "{{item}}"
    state: present
  loop:
    - elrepo-release
    - epel-release
    - kmod-wireguard
    - wireguard-tools

- name: Install Firezone RPM
  ansible.builtin.yum:
    name: "{{firezone_github_url}}/{{firezone_version}}/firezone_{{firezone_version}}-centos8-x64.rpm"
    state: present
    disable_gpg_check: true

