---
- name: Install Promtail
  become: true
  apt:
    name: promtail
    update_cache: yes
    state: present

- name: Ensure Promtail service is enabled and started
  become: true
  service:
    name: promtail
    enabled: yes
    state: started
