---
- name: Install Promtail
  become: true
  apt:
    name: promtail
    update_cache: yes
    state: present

- name: Ensure Promtail service is enabled and started
  become: true
  service:
    name: promtail
    enabled: yes
    state: started

- name: Set Promtail input sources
  copy:
    src: promtail-input-sources.yaml
    dest: /etc/promtail/input-sources.yaml
    mode: '0644'

- name: Set Promtail parsing rules
  copy:
    src: promtail-parsing-rules.yaml
    dest: /etc/promtail/parsing-rules.yaml
    mode: '0644'

- name: Set Loki endpoint in Promtail configuration
  replace:
    path: /etc/promtail/config.yaml
    regexp: 'http://localhost:3100'
    replace: '{{ loki_endpoint }}'

