server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system_logs
    pipeline_stages:
      - json:
          expressions:
            stream: journal_stream
      - regex:
          expression: "^(?P<time>\\S+ \\S+ \\S+) (?P<syslog_host>[^ ]+) (?P<program>[^\\[]+)\\[(?P<pid>\\d+)\\]: (?P<message>.*)$"
        source: message
        action: replace
      - labels:
          syslog_host: syslog_host
          program: program
          pid: pid
    relabel_configs:
      - source_labels: [__journal__systemd_unit]
        regex: "(.*)\\.service"
        target_label: systemd_service
      - source_labels: [__journal__hostname]
        target_label: instance
      - source_labels: [__journal__systemd_unit]
        regex: "(.*)\\.service"
        action: drop
