---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance-el8
    image: quay.io/rockylinux/rockylinux:8
    privileged: true
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: "/usr/sbin/init"
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
verifier:
  name: ansible
