---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:

    - name: Get prometheus service
      ansible.builtin.service:
        name: prometheus
      register: prometheus_status

    - name: verify status of prometheus
      ansible.builtin.assert:
        that: prometheus_status.status.Result == "success"

    - name: Get alertmanager service
      ansible.builtin.service:
        name: alertmanager
      register: alertmanager_status

    - name: verify status of alertmanager
      ansible.builtin.assert:
        that: alertmanager_status.status.Result == "success"
