---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: custom-repo-el9
    image: eniocarboni/docker-rockylinux-systemd:9
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/usr/sbin/init"
    pre_build_image: true
    cgroupns_mode: host
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
verifier:
  name: ansible
