---
# http://prometheus.io/docs/introduction/getting_started/
#
- name: set internal variables for convenience
  set_fact:
    prometheus_node_exporter_tarball_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ prometheus_node_exporter_version }}/node_exporter-{{ prometheus_node_exporter_version }}.{{ prometheus_platform_suffix }}.tar.gz"
    prometheus_node_exporter_daemon_dir: "{{ prometheus_install_path }}/node_exporter-{{ prometheus_node_exporter_version }}.{{ prometheus_platform_suffix }}"

- name: download and untar node_exporter tarball
  unarchive:
    src: "{{ prometheus_node_exporter_tarball_url }}"
    dest: "{{ prometheus_install_path }}"
    copy: no

- name: set permissions, owner and group
  file:
    path: "{{ prometheus_node_exporter_daemon_dir }}/node_exporter"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "go-w"

- name: mkdir for data
  file:
    path: "{{ prometheus_db_path }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "u=rwx,g=rx,o="

# - debug: var=node_exporter_config
#   notify: reload node_exporter
#   when: node_exporter_config.changed

- name: copy systemd config to server
  template: src="../templates/node_exporter.service.j2"  dest="/etc/systemd/system/node_exporter.service"
  notify: restart node_exporter

- name: Enable node_exporter service
  ansible.builtin.service:
    name: node_exporter
    enabled: yes
