---
- name: create Prometheus group
  group:
    name: "{{ prometheus_group }}"
    system: true
    state: present
  tags:
    - prometheus-server

- name: create Prometheus user
  user:
    name: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    system: true
    createhome: false
    shell: /sbin/nologin
    comment: "Prometheus User"
    home: "{{ prometheus_db_path }}"
    state: present
  tags:
    - prometheus-server

- name: mkdir for general cases
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "u=rwx,g=rx,o="
  with_items:
    - "{{ prometheus_install_path }}"
    - "{{ prometheus_config_path }}"
    - "{{ prometheus_log_path }}"
    - "{{ prometheus_pid_path }}"
  tags:
    - prometheus-server

- name: install prometheus
  import_tasks: install-prometheus.yml
  when: '"prometheus" in prometheus_components'
  tags:
    - prometheus-server

- name: install alertmanager
  import_tasks: install-alertmanager.yml
  when: '"alertmanager" in prometheus_components'
  tags:
    - prometheus-server
