---
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yaml"
        - "{{ ansible_distribution }}.yaml"
      paths:
        - '{{role_path}}/vars'
  when: docker_compose_definitions
  tags:
    - docker_compose

- name: install packages for docker module
  package:
    name: "{{item}}"
    state: present
  loop: "{{docker_compose_packages}}"
  when: docker_compose_definitions
  tags:
    - docker_compose

- name: configure docker networks
  community.docker.docker_network:
    name: "{{item.name}}"
  loop: "{{docker_compose_networks}}"
  when: docker_compose_definitions
  tags:
    - docker_compose
    - docker_compose_networks

- name: make docker-compose directories
  include_tasks: docker_directory.yaml
  loop_control:
    loop_var: compose_item
  loop: "{{docker_compose_definitions}}"
  tags:
    - docker_compose
    - docker_compose_definitions

