{
 "title": "Network Traffic",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ethernet Transmit Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_errs_total{device=~\"en.*\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Ethernet Receive Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_errs_total{device=~\"en.*\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ethernet Transmitted (Bytes/Sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{device=~\"en.*\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Ethernet Received (Bytes/Sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=~\"en.*\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Infiniband Transmitted (Bytes/Sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(node_infiniband_port_data_transmitted_bytes_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Infiniband Received (Bytes/Sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_infiniband_port_data_received_bytes_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}