{
 "title": "SLURM Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Cluster Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "slurm_nodes_alloc", "legendFormat": "Allocated Nodes" },
    { "expr": "slurm_nodes_comp", "legendFormat": "Completing Nodes" },
    { "expr": "slurm_nodes_idle", "legendFormat": "Idle Nodes" },
    {
     "expr": "slurm_nodes_alloc + slurm_nodes_down + slurm_nodes_drain + slurm_nodes_idle + slurm_nodes_mix + slurm_nodes_comp + slurm_nodes_maint",
     "legendFormat": "Total Nodes"
    }
   ]
  },
  {
   "title": "Fail/Down/Drain/Err Nodes",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "slurm_nodes_down", "legendFormat": "Down Nodes" },
    { "expr": "slurm_nodes_drain", "legendFormat": "Draining Nodes" },
    { "expr": "slurm_nodes_err", "legendFormat": "Nodes in *error* state" },
    { "expr": "slurm_nodes_fail", "legendFormat": "Nodes in *fail* state" },
    { "expr": "slurm_nodes_maint", "legendFormat": "Nodes in maint state" }
   ]
  },
  { "title": "SLURM Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "RUNNING/COMPL/PEND Jobs",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "slurm_queue_completing", "legendFormat": "Completing Jobs" },
    { "expr": "slurm_queue_running", "legendFormat": "Running Jobs" },
    { "expr": "slurm_queue_pending", "legendFormat": "Pending Jobs" },
    { "expr": "slurm_queue_completed", "legendFormat": "Completed Jobs" }
   ]
  },
  {
   "title": "FAIL/SUSP/CANC/PREEMPT/TIMEDOUT Jobs",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "slurm_queue_timeout", "legendFormat": "Timed out Jobs" },
    { "expr": "slurm_queue_failed", "legendFormat": "Failed Jobs" },
    { "expr": "slurm_queue_node_fail", "legendFormat": "Failed jobs (due to NodeFail)" },
    { "expr": "slurm_queue_suspended", "legendFormat": "Suspended Jobs" },
    { "expr": "slurm_queue_cancelled", "legendFormat": "Cancelled Jobs" },
    { "expr": "slurm_queue_preempted", "legendFormat": "Preempted Jobs" }
   ]
  },
  { "title": "SLURM Scheduler Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Slurm Scheduler Threads",
   "type": "singlestat",
   "description": "The number of current active slurmctld threads.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "slurm_scheduler_threads", "legendFormat": "Slurm Scheduler Threads" }
   ]
  },
  {
   "title": "Agent Queue Size",
   "type": "singlestat",
   "description": "The agent mechanism helps to control communication between the Slrum daemons and the controller for a best effort.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "slurm_scheduler_queue_size", "legendFormat": "Agent Queue Size" }
   ]
  },
  {
   "title": "Scheduler Backfill Depth Mean",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "slurm_scheduler_backfill_depth_mean",
     "legendFormat": "Mean of processed jobs during backfilling scheduling cycles"
    }
   ]
  },
  { "title": "SLURM Scheduler Cycles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Scheduler Cycles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    { "expr": "slurm_scheduler_last_cycle", "legendFormat": "Scheduler Last Cycle Time" },
    { "expr": "slurm_scheduler_mean_cycle", "legendFormat": "Scheduler Mean Cycle Time" }
   ]
  },
  {
   "title": "Backfill Scheduler Cycles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "slurm_scheduler_backfill_last_cycle",
     "legendFormat": "Scheduler Backfill Last Cycle"
    },
    {
     "expr": "slurm_scheduler_backfill_mean_cycle",
     "legendFormat": "Scheduler Backfill Mean Cycle"
    }
   ]
  }
 ]
}