---
- name: Create nodeusr account to run cgroup_exporter
  user:
    name: nodeusr
    shell: /sbin/nologin
    home: /var/lib/node_exporter
    uid: "{{ prometheus_exporter_uid }}"

- name: Extract cgroup_exporter downloaded tarball
  unarchive:
    src: "https://github.com/treydock/cgroup_exporter/releases/download/v{{ cgroup_exporter_version }}/cgroup_exporter-{{ cgroup_exporter_version }}.linux-amd64.tar.gz"
    dest: "{{ cgroup_exporter_executable_path }}"
    owner: nodeusr
    group: nodeusr
    mode: 0755
    remote_src: yes

- name: Create systemd service file
  template:
    src: cgroup_exporter.service.j2
    dest: /etc/systemd/system/cgroup_exporter.service

- name: Enable the systemd service file manually
  file:
    state: link
    src: /etc/systemd/system/cgroup_exporter.service
    dest: /etc/systemd/system/multi-user.target.wants/cgroup_exporter.service

- name: Start the systemd service file if this is not a chroot
  service:
    name: cgroup_exporter
    state: started
  when: ansible_is_chroot == False
