# Extracts blackbox_exporter from a shared tarball and installs onto the specified inventory.
# Creates a systemd file for starting, without actually using systemd. Design
# decision was made to not use systemd for use with images
# NOTE:
# * Targets a particular version release for consistency
---
- name: Create nodeusr account to run blackbox_exporter
  user:
    name: nodeusr
    shell: /sbin/nologin
    home: /var/lib/node_exporter
    uid: 440

- name: Extract blackbox_exporter downloaded tarball
  unarchive:
    src: "https://github.com/prometheus/blackbox_exporter/releases/download/v{{exporter_version}}/blackbox_exporter-{{exporter_version}}.linux-amd64.tar.gz"
    dest: "{{exporter_path}}"
    owner: nodeusr
    group: nodeusr
    remote_src: yes

- name: Create systemd service file
  template:
    src: blackbox_exporter.service.j2
    dest: /etc/systemd/system/blackbox_exporter.service

- name: Enable the systemd service file manually
  file:
    state: link
    src: /etc/systemd/system/blackbox_exporter.service
    dest: /etc/systemd/system/multi-user.target.wants/blackbox_exporter.service
      
- name: Start the systemd service file if this is not a chroot
  service:
    name: blackbox_exporter
    state: started
  when: not ansible_is_chroot
