---
# tasks file for munge
#
- name: Gather os specific variables
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "{{ansible_os_family}}.yaml"
      - "{{ansible_os_family}}-{{ansible_distribution_major_version}}.yaml"
      paths:
        - "{{role_path}}/vars"
  tags:
    - munge

- name: Install munge-devel for EL8
  ansible.builtin.dnf:
    name: munge-devel
    enablerepo: powertools
    state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '8'
  tags:
    - munge

- name: Install packages for Munge
  ansible.builtin.package:
    name: "{{item}}"
    state: present
  loop: "{{munge_packages}}"
  tags:
    - munge

- name: create munge keyfile
  ansible.builtin.copy:
    dest: "/etc/munge/munge.key"
    content: "{{munge_key}}"
    owner: "{{munge_user}}"
    mode: "0400"
  notify:
    - Restart munge
  tags:
    - munge

- name: get status of munge
  shell: "systemctl start munge.service; journalctl -u munge -n 200"
  register: out

- name: Debug munge
  debug:
    msg: "{{out}}"

- name: Enable munge service
  service:
    name: munge
    state: started
    enabled: true
  tags:
    - munge

- name: get status of munge
  shell: systemctl status munge.service
  register: out
- name: Debug munge
  debug:
    msg: "{{out}}"
