---
# tasks file for munge
#
- name: Gather os specific variables
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "{{ansible_os_family}}.yaml"
      - "{{ansible_os_family}}-{{ansible_distribution_major_version}}.yaml"
      paths:
        - "{{role_path}}/vars"
  tags:
    - munge

- name: Install munge-devel for EL8+
  ansible.builtin.dnf:
    name: munge-devel
    enablerepo: "{{ munge_el_repo }}"
    state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version >= '8'
  tags:
    - munge

- name: Install packages for Munge
  ansible.builtin.package:
    name: "{{item}}"
    state: present
  loop: "{{munge_packages}}"
  tags:
    - munge

- name: create munge keyfile
  ansible.builtin.copy:
    dest: "/etc/munge/munge.key"
    content: "{{munge_key}}"
    owner: "{{munge_user}}"
    mode: "0400"
  notify:
    - Restart munge
  tags:
    - munge

- name: Fix munge file if needed
  ansible.builtin.lineinfile:
    backup: true
    path: /lib/systemd/system/munge.service
    state: present
    insertafter: "\\[Install\\]"
    regexp: "^WantedBy=multi-user.target"
    line: "WantedBy=multi-user.target"
  notify:
    - Reload munge
    - Restart munge
  tags:
    - munge

- name: Start munge service
  ansible.builtin.service:
    name: munge
    state: started
    enabled: true
  when: not ansible_is_chroot
  tags:
    - munge

- name: Enable munge on image
  ansible.builtin.shell: systemctl enable munge
  when: ansible_is_chroot
  tags:
    - munge
