---
# tasks file for healtcheck-cron
- name: Create cron job for "{{healtch_check_cron.name}}"
  ansible.builtin.cron:
    name: "{{item.name}}" 
    minute: "{{item.minute | default('0')}}" 
    hour: "{{item.hour | default('*')}}" 
    day: "{{item.day | default('*')}}" 
    weekday: "{{item.weekday | default('*')}}" 
    job: "{{item.command}} && curl -fsS -m 10 --retry 5 -o /dev/null -k {{health_check_base_url}}/ping/{{item.id}}"
    user: root
  loop: "{{health_check_cron}}"
  tags:
    - health
