---
- name: Import VGL GPG Key
  rpm_key:
    state: present
    key: https://www.virtualgl.org/key/VGL-GPG-KEY
  when: ansible_os_family == 'RedHat'

- name: Install VirtualGL
  yum:
    name: "{{ vgl_download }}"
    state: present
  when: ansible_os_family == 'RedHat'

- name: Add 'VGL_DISPLAY=egl' to profile.d
  copy:
    src: vgl_exports.sh
    dest: /etc/profile.d/vgl_exports.sh

# WARNING: These settings are chosen as the environments we use are isolated behind
# a vpn/headnode.
- name: Configure compute node to use VirtualGL
  shell:
    cmd: "/usr/bin/vglserver_config +egl +s +f -t"
  changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"
