---
# tasks file for grafana
- name: Create grafan configuruation directory
  file:
    path: "{{grafana_data_dir}}"
    owner: '472'
    group: '1'
    state: directory
  tags:
    - grafana-server

- name: Set Traefik label
  ansible.builtin.set_fact:
    grafana_docker_labels: 
      traefik.enable: "true"
      traefik.http.routers.grafana.entrypoints: "websecure"
      traefik.http.routers.grafana.rule: "Host(`{{grafana_site_root}}`)"
      traefik.http.routers.grafana.tls: "true"
      traefik.http.routers.grafana.tls.certresolver: letsencrypt
      traefik.http.services.grafana.loadbalancer.server.port: "3000"
      traefik.docker.network: traefik_proxy
    grafana_docker_networks:
      - name: "{{grafana_traefik_network}}"
    grafana_docker_ports: []
  when: grafana_traefik_enable
  tags:
    - grafana-server

- name: Create grafana docker container
  community.docker.docker_container:
    name: "grafana"
    image: "grafana/grafana:{{grafana_version}}"
    restart_policy: always
    network_mode: 'default'
    container_default_behavior: 'no_defaults'
    env:
      GF_PATHS_LOGS: "/var/lib/grafana/logs"
      GF_LOG_MODE: "console file"
      GF_SECURITY_ADMIN_USER: "{{grafana_admin_user}}"
      GF_SECURITY_ADMIN_PASSWORD: "{{grafana_admin_password}}"
      GF_INSTANCE_NAME: "{{grafana_instance_name}}"
    volumes:
      - "{{grafana_data_dir}}:/var/lib/grafana"
    labels: "{{grafana_docker_labels}}"
    networks: "{{grafana_docker_networks}}"
    ports: "{{grafana_docker_ports}}"
  tags:
    - grafana-server


