---
# tasks file for grafana-server-dev
- name: permit traffic in default zone on port 3000/tcp
  ansible.posix.firewalld:
    port: 3000/tcp
    permanent: yes
    state: enabled

- name: install grafana rpm key
  rpm_key:
    key: https://packages.grafana.com/gpg.key
    state: present

- name: install grafana  rpm repository
  yum_repository:
    name: grafana
    description: grafana packages
    baseurl: https://packages.grafana.com/oss/rpm
    gpgcheck: true
    gpgkey: https://packages.grafana.com/gpg.key

- name: install grafana
  yum:
    name: grafana
    state: present

- name: grafana is installed
  yum:
    name=grafana
    state=installed
  retries: 5
  delay: 2
  notify: restart grafana

- name: grafana is running and enabled
  service:
    name=grafana-server
    state=started
    enabled=yes

# - name: Disabling SELinux state
#   selinux:
#     state: disabled
#   notify:
#     - restart server

- name: create prometheus datasource
  community.grafana.grafana_datasource:
    name: dst_prometheus
    ds_type: prometheus
    ds_url: "{{ datasource_url }}"
    url: "{{ grafana_url }}"
    is_default: yes
    # access: proxy
    # tls_skip_verify: true
    # additional_json_data:
    #   httpHeaderName1: "Authorization"
    # additional_secure_json_data:
    #   httpHeaderValue1: "Bearer ihavenogroot"


# - name: Import Grafana dashboard Node Exporter
#   community.grafana.grafana_dashboard:
#     grafana_url: "{{ grafana_url }}"
#     # grafana_api_key: "{{ grafana_api_key }}"
#     # folder: node_exporter
#     overwrite: yes
#     dashboard_id: 1860

- name: copy dashboard files to server
  copy:
    src: "../files/{{item}}"
    dest: /tmp/
    # owner: root
    # group: root
    # mode: 0644
  loop:
    - slurm_dashboard.json
    - node-exporter-full_rev26.json
    - nvidia_dcgm.json
    - s-m-a-r-t-disk-monitoring-for-prometheus-dashboard_rev1.json
    - smart-disk-data_rev2.json

- name: Import Grafana dashboard slurm_dashboard.json
  community.grafana.grafana_dashboard:
    grafana_url: "{{ grafana_url }}"
    # grafana_api_key: "{{ grafana_api_key }}"
    state: present
    commit_message: Updated by ansible
    overwrite: yes
    path: /tmp/slurm_dashboard.json

- name: Import Grafana dashboard node-exporter-full_rev26.json
  community.grafana.grafana_dashboard:
    grafana_url: "{{ grafana_url }}"
    # grafana_api_key: "{{ grafana_api_key }}"
    state: present
    commit_message: Updated by ansible
    overwrite: yes
    path: /tmp/node-exporter-full_rev26.json

- name: Import Grafana dashboard nvidia_dcgm.json
  community.grafana.grafana_dashboard:
    grafana_url: "{{ grafana_url }}"
    # grafana_api_key: "{{ grafana_api_key }}"
    state: present
    commit_message: Updated by ansible
    overwrite: yes
    path: /tmp/nvidia_dcgm.json

- name: Import SMART disk monitoring for Prometheus Dashboard
  community.grafana.grafana_dashboard:
    grafana_url: "{{ grafana_url }}"
    # grafana_api_key: "{{ grafana_api_key }}"
    state: present
    commit_message: Updated by ansible
    overwrite: yes
    path: /tmp/s-m-a-r-t-disk-monitoring-for-prometheus-dashboard_rev1.json

- name: Import SMART disk data Dashboard
  community.grafana.grafana_dashboard:
    grafana_url: "{{ grafana_url }}"
    # grafana_api_key: "{{ grafana_api_key }}"
    state: present
    commit_message: Updated by ansible
    overwrite: yes
    path: /tmp/smart-disk-data_rev2.json