# Extracts node_exporter from a shared tarball and installs onto the specified inventory.
# Creates a systemd file for starting, without actually using systemd. Design
# decision was made to not use systemd for use with images
---
- name: Create nodeusr account to run node_exporter
  user:
    name: nodeusr
    shell: /sbin/nologin
    home: /var/lib/node_exporter
    uid: "{{ uid }}"
  tags:
    - prometheus_node_exporter

- name: Extract node_exporter downloaded tarball
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version  }}/node_exporter-{{ node_exporter_version  }}.linux-amd64.tar.gz"
    dest: "/var/lib/node_exporter/"
    owner: nodeusr
    group: nodeusr
    remote_src: yes
  tags:
    - prometheus_node_exporter

- name: Create systemd service file
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
  tags:
    - prometheus_node_exporter

- name: Enable the systemd service file manually
  file:
    state: link
    src: /etc/systemd/system/node_exporter.service
    dest: /etc/systemd/system/multi-user.target.wants/node_exporter.service
  tags:
    - prometheus_node_exporter

- name: Create textfile_collector directory
  file:
    path: /var/lib/node_exporter/textfile_collector
    state: directory
    mode: 0755
  tags:
    - prometheus_node_exporter
      
- name: Start the systemd service file if this is not a chroot
  service:
    name: node_exporter
    state: started
  when: not ansible_is_chroot
  tags:
    - prometheus_node_exporter

- name: Verify that smartmontools is installed
  yum:
    name: smartmontools
    state: latest
  when: ansible_distribution == 'CentOS'
  tags:
    - prometheus_node_exporter

- name: Verify that smartmontools is installed
  package:
    name: smartmontools
    state: latest
  when: ansible_distribution == 'Debian'
  tags:
    - prometheus_node_exporter

- name: Fetch smartmon shell script file
  copy:
    src: "smartmon.sh"
    dest: "/var/lib/node_exporter/smartmon.sh"
    mode: 0755
  tags:
    - prometheus_node_exporter

- name: Crontab the smartmon shell script file
  cron:
    name: "run smartmon.sh to node_exporter collector"
    special_time: hourly
    job: "/var/lib/node_exporter/smartmon.sh > /var/lib/node_exporter/textfile_collector/smart_status.prom 2>&1"
  tags:
    - prometheus_node_exporter
