- name: Install Loki
  ansible.builtin.get_url:
    url: "{{ loki_binary_url }}"
    dest: "/tmp/{{ loki_binary_name }}"
    mode: '0644'
  become: true
  tags: [loki]

- name: Extract Loki
  unarchive:
    src: "/tmp/{{ loki_binary_name }}"
    dest: "{{ loki_install_dir }}"
    remote_src: true
    copy: false
  become: true
  tags: [loki]

- name: Configure Loki
  template:
    src: loki-config.yaml.j2
    dest: "{{ loki_config_path }}"
  become: true
  tags: [loki]

- name: Create Loki Systemd Service
  template:
    src: loki.service.j2
    dest: "{{ loki_systemd_path }}"
  become: true
  tags: [loki]

- name: Create Loki directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ loki_config_dir }}"
    - "{{ loki_data_dir }}"
  tags: [loki]

- name: Enable and Start Loki Systemd Service
  systemd:
    name: loki
    enabled: true
    state: started
  become: true
  tags: [loki]
