promtail_version: "2.7.4"
promtail_http_listen_port: "9080"
promtail_config:
  server:
    http_listen_port: 9080
  positions:
    filename: /tmp/positions.yaml
    bad_actor_duration: 24h
promtail_targets:
  - job_name: system
    static_configs:
      - targets: ['localhost']
        labels:
          job: varlogs
          __path__: /var/log/*log
