---
# tasks file for postresql-pitr
#
- name: set archive one
  lineinfile:
    path: "{{pitr_postgresql_postgresql_file}}"
    regexp: "^archive_mode"
    insertafter: "^#archive_mode"
    line: "archive_mode = on"
  tags:
    - postgresql-pitr

- name: set wal level
  lineinfile:
    path: "{{pitr_postgresql_postgresql_file}}"
    regexp: "^wal_level"
    insertafter: "^#wal_level"
    line: "wal_level = replica"
  tags:
    - postgresql-pitr

- name: set archive command
  lineinfile:
    path: "{{pitr_postgresql_postgresql_file}}"
    regexp: "^archive_command"
    insertbefore: "^#archive_command"
    line: "archive_command = 'test ! -f {{pitr_postgresql_archive_dir}}/%f && cp %p {{pitr_postgresql_archive_dir}}/%f'"
  tags:
    - postgresql-pitr
