---
# set default when running against chroot
ansible_processor_count: "2"
# variables to be defined in user's playbook to specify prometheus component
prometheus_components:
  - prometheus
  # - node_exporter
  # - alertmanager

alertmanager_slack_api_url: ''
alertmanager_slack_channel: ''
alertmanager_opsgenie_api_key: ''
alertmanager_opsgenie_team: ''
alertmanager_opsgenie_heartbeat_name: ''

alertmanager_resolve_timeout: 1m
# user-configurable defaults
#
prometheus_user:   prometheus
prometheus_group:  prometheus

prometheus_version:                 2.41.0
prometheus_node_exporter_version:   1.3.1
prometheus_alertmanager_version:    0.25.0
prometheus_systemd_version: 219
prometheus_platform_suffix: "linux-amd64"

prometheus_install_path:         /opt/prometheus
prometheus_config_path:          /etc/prometheus
prometheus_rule_path:            "{{ prometheus_config_path }}/rules"
prometheus_file_sd_config_path:  "{{ prometheus_config_path }}/tgroups"
prometheus_db_path:              /var/lib/prometheus
prometheus_log_path:             /var/log/prometheus
prometheus_pid_path:             /var/run/prometheus
prometheus_alertmanager_db_path: /var/lib/alertmanager
prometheus_read_only_dirs: []

prometheus_slurm_exporter_host: localhost
prometheus_blackbox_exporter_host: localhost:9115

prometheus_web_listen_address: "0.0.0.0:9090"
prometheus_web_external_url: ''
prometheus_metrics_path: "/{{ ( prometheus_web_external_url + '/metrics' ) | regex_replace('^(.*://)?(.*?)/') }}"
# See https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md
prometheus_web_config:
  tls_server_config: {}
  http_server_config: {}
  basic_auth_users: {}

prometheus_storage_retention: "365d"
# Available since Prometheus 2.7.0
# [EXPERIMENTAL] Maximum number of bytes that can be stored for blocks. Units
# supported: KB, MB, GB, TB, PB.
prometheus_storage_retention_size: "0"

prometheus_config_flags_extra: {}
# prometheus_config_flags_extra:
#   storage.tsdb.retention: 15d
#   alertmanager.timeout: 10s

prometheus_alertmanager_config: []
# prometheus_alertmanager_config:
#   - scheme: https
#     path_prefix: alertmanager/
#     basic_auth:
#       username: user
#       password: pass
#     static_configs:
#       - targets: ["127.0.0.1:9093"]
#     proxy_url: "127.0.0.2"

prometheus_alert_relabel_configs: []
# prometheus_alert_relabel_configs:
#   - action: labeldrop
#     regex: replica

prometheus_global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

prometheus_remote_write: []

prometheus_remote_read: []

prometheus_external_labels:
  environment: "{{ ansible_fqdn | default(ansible_host) | default(inventory_hostname) }}"

prometheus_targets: {}
#  node:
#    - targets:
#        - localhost:9100
#      labels:
#        env: test

prometheus_scrape_configs:
  - job_name: "prometheus"
    metrics_path: "{{ prometheus_metrics_path }}"
    static_configs:
      - targets:
          - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090"

  - job_name: "node_compute"
    file_sd_configs:
      - files:
          - "{{ prometheus_file_sd_config_path }}/node_compute.yml"
          
  - job_name: "node_service"
    file_sd_configs:
      - files:
          - "{{ prometheus_file_sd_config_path }}/node_service.yml"

  - job_name: "node_storage"
    file_sd_configs:
      - files:
          - "{{ prometheus_file_sd_config_path }}/node_storage.yml"

  - job_name: "cgroups"
    file_sd_configs:
      - files:
          - "{{ prometheus_file_sd_config_path }}/cgroups.yml"

  - job_name: "gpfs"
    file_sd_configs:
      - files:
          - "{{ prometheus_file_sd_config_path }}/gpfs.yml"

  - job_name: "slurm"
    metrics_path: "{{ prometheus_metrics_path }}"
    static_configs:
      - targets:
          - "{{ prometheus_slurm_exporter_host | default('localhost') }}:9200"

  - job_name: "blackbox_icmp"
    file_sd_configs:
      - files:
          - "{{ prometheus_file_sd_config_path }}/blackbox_icmp.yml"
    params:
      module: [icmp]
    metrics_path: "/probe"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "{{prometheus_blackbox_exporter_host}}"

  - job_name: "blackbox_ssh"
    file_sd_configs:
      - files:
          - "{{ prometheus_file_sd_config_path }}/blackbox_ssh.yml"
    params:
      module: [ssh_banner]
    metrics_path: "/probe"
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*?)(:.*)?
        replacement: ${1}:22
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "{{prometheus_blackbox_exporter_host}}"

  - job_name: "blackbox_dns"
    file_sd_configs:
      - files:
          - "{{ prometheus_file_sd_config_path }}/blackbox_dns.yml"
    params:
      module: [dns_test]
    metrics_path: "/probe"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "{{prometheus_blackbox_exporter_host}}"

  - job_name: "zfs"
    file_sd_configs:
      - files:
          - "{{ prometheus_file_sd_config_path }}/zfs.yml"

  # Usually port 8000
  - job_name: "vast"
    scrape_interval: 1m
    scrape_timeout: 50s
    file_sd_configs:
      - files:
          - "{{ prometheus_file_sd_config_path }}/vast.yml"
    
  - job_name: "ondemand"
    metrics_path: "/metrics"
    scrape_interval: 20s
    scrape_timeout: 20s
    file_sd_configs:
      - files:
          - "{{ prometheus_file_sd_config_path }}/ondemand.yml"

# Alternative config file name, searched in ansible templates path.
prometheus_config_file: 'prometheus.yml.j2'

prometheus_alert_rules_files:
  - prometheus/rules/*.rules

prometheus_static_targets_files:
  - prometheus/targets/*.yml
  - prometheus/targets/*.json

prometheus_alert_rules: False
