{
 "title": "SMART disk data",
 "description": "Extended smartmon Dashboard for disk SMART data",
 "tags": [
  "prometheus",
  "node_exporter",
  "smartmon"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(smartmon_smartctl_version, instance)"
   },
   {
    "name": "disk",
    "query": "label_values(smartmon_device_smart_available, disk)"
   },
   {
    "name": "type",
    "query": "label_values(smartmon_device_smart_available, type)"
   },
   {
    "name": "device_model",
    "query": "label_values(smartmon_device_smart_available, device_model)"
   },
   {
    "name": "serial_number",
    "query": "label_values(smartmon_device_smart_available, serial_number)"
   },
   {
    "name": "model_family",
    "query": "label_values(smartmon_device_smart_available, model_family)"
   }
  ]
 },
 "panels": [
  {
   "title": "Disk Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(smartmon_temperature_celsius_raw_value{instance=~\"$instance\",disk=~\"$disk\",type=~\"$type\",serial_number=~\"$serial_number\",model_family=~\"$model_family\",device_model=~\"$device_model\"}) by (device_model,serial_number)",
     "legendFormat": "{{device_model}} (S/N: {{serial_number}})"
    }
   ]
  },
  {
   "title": "Unhealthy Disks",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "  max(smartmon_device_smart_healthy{instance=~\"$instance\",disk=~\"$disk\",type=~\"$type\",serial_number=~\"$serial_number\",model_family=~\"$model_family\",device_model=~\"$device_model\"}) by (disk,device_model,serial_number) < 1"
    }
   ]
  },
  {
   "title": "Pending and Reallocated Sectors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smartmon_reallocated_sector_ct_raw_value{instance=~\"$instance\",disk=~\"$disk\",type=~\"$type\",serial_number=~\"$serial_number\",model_family=~\"$model_family\",device_model=~\"$device_model\"} > 0",
     "legendFormat": "Reallocated {{disk}}"
    },
    {
     "expr": "smartmon_current_pending_sector_raw_value{instance=~\"$instance\",disk=~\"$disk\",type=~\"$type\",serial_number=~\"$serial_number\",model_family=~\"$model_family\",device_model=~\"$device_model\"} > 0",
     "legendFormat": "Pending {{disk}}"
    }
   ]
  },
  {
   "title": "Disk Lifetime",
   "type": "table",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "max(smartmon_power_on_hours_raw_value{instance=~\"$instance\",disk=~\"$disk\",type=~\"$type\",serial_number=~\"$serial_number\",model_family=~\"$model_family\",device_model=~\"$device_model\"}) by (device_model,serial_number)"
    },
    {
     "expr": "max(smartmon_load_cycle_count_raw_value{instance=~\"$instance\",disk=~\"$disk\",type=~\"$type\",serial_number=~\"$serial_number\",model_family=~\"$model_family\",device_model=~\"$device_model\"}) by (device_model,serial_number)",
     "legendFormat": "Load Cycles"
    }
   ]
  },
  {
   "title": "Wear Level on SSDs",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 10 },
   "targets": [
    {
     "expr": "sort_desc(100 - smartmon_wear_leveling_count_value {instance=~\"$instance\",disk=~\"$disk\",type=~\"$type\",serial_number=~\"$serial_number\",model_family=~\"$model_family\",device_model=~\"$device_model\"})",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Total Data Written on SSDs",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 16 },
   "targets": [
    {
     "expr": "(smartmon_total_lbas_written_raw_value{instance=~\"$instance\",disk=~\"$disk\",type=~\"$type\",serial_number=~\"$serial_number\",model_family=~\"$model_family\",device_model=~\"$device_model\"} * on(disk,instance,device_model,serial_number) smartmon_device_sector_size_logical)",
     "legendFormat": "{{disk}} ({{device_model}}, sn: {{serial_number}})"
    },
    {
     "expr": "(100 - smartmon_wear_leveling_count_value {instance=~\"$instance\",disk=~\"$disk\",type=~\"$type\",serial_number=~\"$serial_number\",model_family=~\"$model_family\",device_model=~\"$device_model\"})"
    }
   ]
  },
  {
   "title": "Raw Error Read Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(smartmon_raw_read_error_rate_raw_value{instance=~\"$instance\",disk=~\"$disk\",type=~\"$type\",serial_number=~\"$serial_number\",model_family=~\"$model_family\",device_model=~\"$device_model\"}) by (device_model,serial_number) > 0",
     "legendFormat": "{{device_model}} (S/N: {{serial_number}})"
    }
   ]
  }
 ]
}