---
- name: Create nodeusr account to run lustre_exporter
  user:
    name: nodeusr
    shell: /sbin/nologin
    home: /var/lib/node_exporter
    uid: "{{ prometheus_exporter_uid }}"
  tags:
    - lustre_exporter

- name: Extract go downloaded tarball
  unarchive:
    src: https://go.dev/dl/go1.19.5.linux-amd64.tar.gz
    dest: /tmp
    owner: nodeusr
    group: nodeusr
    mode: 0755
    validate_certs: no
    remote_src: yes
  tags:
    - lustre_exporter

- name: Clone a github repository
  git:
    repo: https://github.com/dstdev/lustre_exporter.git
    dest: /tmp/lustre_exporter
    clone: yes
    update: yes
  environment:
    - GIT_SSL_NO_VERIFY: "true"
  tags:
    - lustre_exporter
    
- name: Stop the systemd service file if this is not a chroot
  service:
    name: lustre_exporter
    state: stopped
  when: ansible_is_chroot == False
  tags:
    - never
    - lustre_exporte

- name: Compile and install lustre_exporter
  become: yes
  shell: "make build && chown nodeusr:nodeusr lustre_exporter && mkdir -p {{ lustre_exporter_executable_path }} && cp /tmp/lustre_exporter/lustre_exporter {{ lustre_exporter_executable_path }}"
  environment:
    PATH: "/tmp/go/bin:{{ ansible_env.PATH }}"
  args:
    chdir: /tmp/lustre_exporter
  tags:
    - lustre_exporter

- name: Create systemd service file
  template:
    src: lustre_exporter.service.j2
    dest: /etc/systemd/system/lustre_exporter.service
  tags:
    - lustre_exporter

- name: Enable the systemd service file manually
  file:
    state: link
    src: /etc/systemd/system/lustre_exporter.service
    dest: /etc/systemd/system/multi-user.target.wants/lustre_exporter.service
  tags:
    - lustre_exporter

- name: Start the systemd service file if this is not a chroot
  service:
    name: lustre_exporter
    state: started
    enabled: yes
  when: ansible_is_chroot == False
  tags:
    - lustre_exporter
    - start_systemd

- name: cleanup tmp files
  become: yes
  shell: "rm -rf /tmp/lustre_exporter && rm -rf /tmp/go"
  args:
    chdir: /tmp
  tags:
    - lustre_exporter
    - cleanup

- name: add nodeuser to soduer file
  become: yes
  lineinfile:
    path: "/etc/sudoers"
    line: "nodeusr        ALL=(ALL)       NOPASSWD: ALL"
  tags:
    - soduer_file
    - lustre_exporter
