# TODO: Need to import the correct variables
- name: install packages for docker module
  package:
    name: "{{item}}"
    state: present
  loop:
    - python3-docker
    - python3-dockerpty
    - python3-yaml
  tags:
    - traefik

- name: create traefik directories
  file:
    path: "{{traefik_data_dir}}"
    owner: root
    group: root
    state: directory
  tags:
    - traefik

- name: create traefik directories
  file:
    path: "{{traefik_data_dir}}/acme"
    owner: root
    group: root
    state: directory
  tags:
    - traefik

- name: traefik_file_contents
  ansible.builtin.template:
    src: templates/traefik.toml.j2
    dest: "{{traefik_data_dir}}/traefik.toml"
    owner: root
    group: root
    mode: "0660"
  tags:
    - traefik


- name: Create a network
  community.docker.docker_network:
    name: traefik_proxy
  tags:
    - traefik

- name: Start traefik container
  community.docker.docker_container:
    name: traefik
    image: "traefik:v2.2"
    state: started
    restart_policy: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{traefik_data_dir}}/traefik.toml:/etc/traefik/traefik.toml"
      - "{{traefik_data_dir}}/acme:/etc/traefik/acme"
    log_options:
      max-size: "10m"
      max-file: "3"
    networks:
      - name: traefik_proxy
    ports:
      - "443:443"
      - "80:80"
      - "9180:8080"

  tags:
    - traefik
    - traefik-this
