# TODO: Need to import the correct variables
- name: install packages for docker module
  package:
    name: "{{item}}"
    state: present
  loop:
    - python3-docker
    - python3-dockerpty
    - python3-yaml
    - docker-compose
  tags:
    - traefik

- name: create traefik directories
  file:
    path: "{{traefik_data_dir}}"
    owner: root
    group: root
    state: directory
  tags:
    - traefik

- name: create traefik directories
  file:
    path: "{{traefik_data_dir}}/acme"
    owner: root
    group: root
    state: directory
  tags:
    - traefik

- name: traefik_file_contents
  ansible.builtin.template:
    src: templates/traefik.toml.j2
    dest: "{{traefik_data_dir}}/traefik.toml"
    owner: root
    group: root
    mode: "0660"
  tags:
    - traefik


- name: Create a network
  community.docker.docker_network:
    name: traefik_proxy
  tags:
    - traefik

# TODO: Move to straight docker, not docker-compose
- name: docker-compose
  community.docker.docker_compose:
    project_name: traefik
    definition: 
      version: "2.3"
      services:
        traefik:
          image: "traefik:v2.2"
          restart: unless-stopped
          container_name: traefik
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - "{{traefik_data_dir}}/traefik.toml:/etc/traefik/traefik.toml"
            - "{{traefik_data_dir}}/acme:/etc/traefik/acme"
          networks:
            - traefik_proxy
          ports:
            - "443:443/tcp"
            - "80:80/tcp"
            - "9180:8080/tcp"

          logging:
            options:
              max-size: "10m"
              max-file: "3"
      networks:
        traefik_proxy:
          external:
            name: traefik_proxy
    state: present
    pull: yes
  register: output
  tags:
    - traefik

- ansible.builtin.assert:
    that: "output.services.traefik.traefik.state.running"
  tags:
    - traefik
