---
- name: Create nodeusr account to run gpfs_exporter
  user:
    name: nodeusr
    shell: /sbin/nologin
    home: /var/lib/node_exporter
    uid: "{{ uid }}"

- name: Extract gpfs_exporter downloaded tarball
  unarchive:
    src: "https://github.com/topine/ibm-spectrum-exporter/releases/download/v{{ exporter_version }}/ibm-spectrum-exporter_{{ exporter_version  }}_Linux_x86_64.tar.gz"
    dest: "{{ executable_path }}"
    owner: nodeusr
    group: nodeusr
    mode: 0755
    remote_src: yes

- name: Create systemd service file
  template:
    src: ibm_exporter.service.j2
    dest: /etc/systemd/system/ibm_exporter.service

- name: Enable the systemd service file manually
  file:
    state: link
    src: /etc/systemd/system/ibm_exporter.service
    dest: /etc/systemd/system/multi-user.target.wants/ibm_exporter.service

- name: Start the systemd service file if this is not a chroot
  service:
    name: gpfs_exporter
    state: started
  when: not ansible_is_chroot
