---
# tasks file for moosefs-client
- name: Gather os specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family }}.yaml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}\
           .yaml"
      paths:
        - "{{ role_path }}/vars"
  tags:
    - moosefs-client

- name: Add moosefs repository
  ansible.builtin.yum_repository:
    name: MooseFS
    description: MooseFS $releasever - $basearch
    baseurl: "{{moosefs_base_url}}"
    gpgkey: "{{moosefs_gpg_key}}"
    gpgcheck: yes
    enabled: yes
  tags:
    - moosefs-client

- name: Install moosefs-client
  ansible.builtin.package:
    name: moosefs-client
    state: present
  tags:
    - moosefs-client

