---
# tasks file for slurm-controller
- name: Configure firewalld
  block:
    - name: Install required firewall packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{slurm_firewalld_packages}}"

    - name: Open internal network
      ansible.posix.firewalld:
        rich_rule: "rule family=ipv4 source address={{slurm_firewalld_subnet}} port port=6817-6819 protocol=tcp accept"
        state: enabled
        permanent: true
        zone: internal
      vars:
        ansible_python_interpreter: "{{slurm_firewalld_python_interpreter}}"
      notify: Reload firewalld

  when: slurm_firewalld_enabled
  become: yes
  tags:
    - slurm
    - slurm_firewall
