---

- name: Gather os specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family }}.yaml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}\
           .yaml"
      paths:
        - "{{ role_path }}/vars"
  tags:
    - slurm
    - slurm_install_controller
    - slurm_install_slurmd

- name: Set slurm download version
  ansible.builtin.set_fact:
    slurm_download_version: "{{ slurm_version | replace('.', '-')}}"
  tags:
    - slurm
    - slurm_install_controller
    - slurm_install_slurmd

- name: Update slurm download version
  ansible.builtin.set_fact:
    slurm_download_version: "{{ slurm_download_version }}-1"
  when: "{{ slurm_download_version.split('-') | length }} < 4"
  tags:
    - slurm
    - slurm_install_controller
    - slurm_install_slurmd

- name: Include install tasks
  ansible.builtin.include_tasks: "install.yaml"
  tags:
    - any

- name: Include firewall tasks
  ansible.builtin.include_tasks: "firewall.yaml"
  tags:
    - always

- name: Include slurmdbd tasks
  ansible.builtin.include_tasks: "slurmdbd.yaml"
  when: slurm_controller
  tags:
    - any

- name: Include slurmctld tasks
  ansible.builtin.include_tasks: "slurmctld.yaml"
  when: slurm_controller
  tags:
    - any

- name: Include slurmrestd tasks
  ansible.builtin.include_tasks: "slurmrestd.yaml"
  when: slurm_controller and slurm_enable_restd
  tags:
    - any
    
- name: Include slurmd tasks
  ansible.builtin.include_tasks: "slurmd.yaml"
  when: slurm_slurmd
  tags:
    - any
    
