---
- name: Gather os specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family }}.yaml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}\
           .yaml"
      paths:
        - "{{ role_path }}/vars"
  tags:
    - always

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: "auto"
    
#- name: Include NVML validation tasks
#  ansible.builtin.include_tasks: "validate_nvml.yml"
#  tags:
#    - always
    
##################################################
# Exits role after the rpmbuild(s) are complete.
- name: Build RPM packages if needed 
  ansible.builtin.include_tasks: "rpmbuild.yaml"
  when: slurm_build_rpms
# role exits early if slurm_build_rpms == true 
##################################################


- name: Check install method
  fail: 
    msg:
      - "slurm_rpm_install and slurm_source_install are mutually exclusive."
  when: slurm_rpm_install and slurm_source_install

- name: Include pre-install tasks
  ansible.builtin.include_tasks: "pre_install.yaml"
  tags:
    - always

- name: Check if Slurm Version is above 24.05.8-0
  ansible.builtin.include_tasks: "slurm_version_check.yaml"
  tags:
    - always

- name: Fail if both slurm_rpm_install and slurm_source_install 
  ansible.builtin.fail:
    msg: "slurm_rpm_install and slurm_source_install are mutually exclusive"
  when: slurm_rpm_install and slurm_source_install

- name: Include install tasks
  ansible.builtin.include_tasks: "install.yaml"
  tags:
    - always
  when: slurm_source_install

- name: Include rpm install tasks
  ansible.builtin.include_tasks: "rpm_install.yaml"
  tags:
    - always
  when: slurm_rpm_install 

- name: Include post-install tasks
  ansible.builtin.include_tasks: "post_install.yaml"
  tags:
    - always

- name: Include firewall tasks
  ansible.builtin.include_tasks: "firewall.yaml"
  tags:
    - always

- name: Include slurmdbd tasks
  ansible.builtin.include_tasks: "slurmdbd.yaml"
  when: slurm_controller
  tags:
    - always

- name: Include slurmctld tasks
  ansible.builtin.include_tasks: "slurmctld.yaml"
  when: slurm_controller
  tags:
    - always

- name: Include slurmrestd tasks
  ansible.builtin.include_tasks: "slurmrestd.yaml"
  when: slurm_controller and slurm_enable_restd
  tags:
    - always
    
- name: Include slurmd tasks
  ansible.builtin.include_tasks: "slurmd.yaml"
  when: slurm_slurmd
  tags:
    - always
    
- name: Include cleaup tasks
  ansible.builtin.include_tasks: "cleanup.yaml"
  tags:
    - always
