- name: Add local custom repo
  yum_repository:
    name: "{{ slurm_local_repo_name }}"
    description: "{{ slurm_local_repo_description }}"
    baseurl: "{{ slurm_rpm_local_repo_url }}"
    gpgcheck: no

- name: Check Command
  ansible.builtin.shell: 
    cmd: "dnf repoquery --repo {{ slurm_local_repo_name }} slurm | awk -F: '{print $2}' | awk -F- '{print $1}'"
  register: slurm_repo_version

- name: Verify repo vs expected version 
  debug:
    msg: 
      - "{{ slurm_repo_version.stdout }}"

- name: Fail on Version mismatch 
  ansible.builtin.fail: 
    msg: "Required Slurm Version {{ slurm_version }} does not match available RPM on repo {{ slurm_repo_version.stdout }}" 
  when: slurm_repo_version.stdout != slurm_version

- name: Install slurm rpm packages 
  yum:
    state: present
    name:
      - slurm
      - slurm-perlapi
      - slurm-libpmi
  tags: 
    - slurm
    - slurm_install_controller
    - slurm_install_slurmd

- name: Install slurm controller rpm packages
  yum:
    state: present
    name:
      - slurm-slurmctld
      - slurm-slurmdbd
  when: slurm_controller
  tags: 
    - slurm
    - slurm_install_controller

- name: Install slurmd rpm packages
  yum:
    state: present
    name:
      - slurm-slurmd
      - slurm-pam_slurm
  when: slurm_slurmd
  tags:
    - slurm
    - slurm_install_slurmd

- name: Install slurmrestd rpm packages
  yum:
    state: present
    name:
      - slurm-slurmrestd
  when: slurm_controller and slurm_enable_restd 
  tags:
    - slurm
    - slurm_install_controller
    - slurm_install_restd


- name: Add jwt key
  command:  "dd if=/dev/random of=/var/spool/slurmctld/jwt_hs256.key bs=32 count=1"
  when: slurm_controller and slurm_enable_restd 
  tags:
    - slurm
    - slurm_install_controller
    - slurm_install_restd

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /var/spool/slurmctld/jwt_hs256.key
    owner: "{{ slurm_user }}"
    group: "{{ slurm_user }}"
    mode: '0600'
  when: slurm_controller and slurm_enable_restd 