- name: create slurmd service file
  ansible.builtin.template:
    src: templates/slurmd.service.j2
    dest: /etc/systemd/system/slurmd.service
    owner: root
    group: root
    mode: "0644"
  tags:
    - slurm
    - slurm_install_slurmd
    - slurm_configure

- name: Create slurm configuration directory
  ansible.builtin.file:
    path: /etc/slurm
    state: directory
    owner: slurm
    group: slurm
  tags:
    - slurm
    - slurm_configure

- name: Create prolog scripts
  ansible.builtin.template:
    src: templates/job-prolog.sh.j2
    dest: /etc/slurm/job-prolog.sh
    owner: root
    group: root
    mode: "0755"
  tags:
    - slurm
    - slurm_configure

- name: Create epilog scripts
  ansible.builtin.template:
    src: templates/job-epilog.sh.j2
    dest: /etc/slurm/job-epilog.sh
    owner: root
    group: root
    mode: "0755"
  tags:
    - slurm
    - slurm_configure

- name: Create task prolog scripts
  ansible.builtin.template:
    src: templates/task-prolog.sh.j2
    dest: /etc/slurm/task-prolog.sh
    owner: root
    group: root
    mode: "0755"
  tags:
    - slurm
    - slurm_configure

- name: Create task epilog scripts
  ansible.builtin.template:
    src: templates/task-epilog.sh.j2
    dest: /etc/slurm/task-epilog.sh
    owner: root
    group: root
    mode: "0755"
  tags:
    - slurm
    - slurm_configure

- name: Add slurm pam adopt to pam.d/sshd
  ansible.builtin.blockinfile:
    path: /etc/pam.d/sshd
    state: present
    block: |
      account    sufficient    pam_listfile.so item=group sense=allow onerr=fail file={{ slurm_groups_allowed_path }}
      account    required      pam_slurm_adopt.so
    insertafter: "EOF"
  when: slurm_enable_pam_adopt
  tags:
    - slurm
    - slurm_configure

- name: Populate pam adopt allowed groups
  ansible.builtin.lineinfile:
    path: "{{ slurm_groups_allowed_path }}"
    state: present
    line: "{{ item }}"
    insertafter: "EOF"
    create: true
  loop: "{{ slurm_groups_allowed }}"
  when: slurm_enable_pam_adopt
  tags:
    - slurm
    - slurm_configure
  

- name: Create unkillable step script
  ansible.builtin.template:
    src: templates/kill_step.sh.j2
    dest: /etc/slurm/kill_step.sh
    owner: root
    group: root
    mode: "0755"
  tags:
    - slurm
    - slurm_configure

- name: Start slurmd service
  ansible.builtin.service:
    name: slurmd
    state: started
    enabled: true
  when: not ansible_is_chroot
  tags:
    - slurm
    - slurm_install_slurmd

- name: Enable slurmd on image
  ansible.builtin.shell: systemctl enable slurmd
  when: ansible_is_chroot
  tags:
    - slurm
    - slurm_install_slurmd
