---
- name: create slurmrestd service file
  ansible.builtin.template:
    src: templates/slurmrestd.service.j2
    dest: /etc/systemd/system/slurmrestd.service
    owner: root
    group: root
    mode: "0644"
  tags:
    - slurm
    - slurm_install_slurmd
  when: slurm_source_install

- name: create slurmrestd service file
  ansible.builtin.template:
    src: templates/slurmrestd.sysconfig.j2
    dest: /etc/sysconfig/slurmrestd
    owner: root
    group: root
    mode: "0644"
  tags:
    - slurm
    - slurm_install_slurmd
  when: slurm_rpm_install

- name: Create jwt key
  ansible.builtin.copy:
    dest: "{{slurm_state_save_location}}/jwt_hs256.key"
    content: "{{slurm_restd_jwt_key}}"
    owner: "{{slurm_uid}}"
    group: "{{slurm_gid}}"
    mode: "0600"
  tags:
    - slurm_install_restd

- name: Start slurmrestd service
  ansible.builtin.service:
    name: slurmrestd
    state: started
    enabled: true
  when: not ansible_is_chroot
  tags:
    - slurm
    - slurm_install_slurmd
