- name: Create configuration file
  ansible.builtin.template:
    src: templates/slurm.conf.j2
    dest: /etc/slurm/slurm.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart slurmctld
  tags:
    - slurm
    - slurm_configure

- name: Create prolog scripts
  ansible.builtin.template:
    src: templates/job-prolog.sh.j2
    dest: /etc/slurm/job-prolog.sh
    owner: root
    group: root
    mode: "0755"
  notify:
    - Restart slurmctld
  tags:
    - slurm
    - slurm_configure

- name: Create epilog scripts
  ansible.builtin.template:
    src: templates/job-epilog.sh.j2
    dest: /etc/slurm/job-epilog.sh
    owner: root
    group: root
    mode: "0755"
  notify:
    - Restart slurmctld
  tags:
    - slurm
    - slurm_configure

- name: Create cgroup configuration file
  ansible.builtin.template:
    src: templates/cgroup.conf.j2
    dest: /etc/slurm/cgroup.conf
    owner: slurm
    group: slurm
    mode: "0644"
  notify:
    - Restart slurmctld
  tags:
    - slurm
    - slurm_configure

- name: Create slurmctld service file
  ansible.builtin.template:
    src: templates/slurmctld.service.j2
    dest: /etc/systemd/system/slurmctld.service
    owner: root
    group: root
    mode: "0644"
  tags:
    - slurm
    - slurm_install_controller

- name: Start slurmctld service
  ansible.builtin.service:
    name: slurmctld
    state: started
    enabled: true
  tags:
    - slurm
    - slurm_install_controller
