- name: Create configuration file
  ansible.builtin.template:
    src: templates/slurm.conf.j2
    dest: /etc/slurm/slurm.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart slurmctld
  tags:
    - slurm
    - slurm_configure

- name: Create gres configuration file
  ansible.builtin.template:
    src: templates/gres.conf.j2
    dest: /etc/slurm/gres.conf
    owner: root
    group: root
    mode: "0644"
  when: slurm_gres_conf_entries
  notify:
    - Restart slurmctld
  tags:
    - slurm
    - slurm_configure

- name: Create cgroup configuration file
  ansible.builtin.template:
    src: templates/cgroup.conf.j2
    dest: /etc/slurm/cgroup.conf
    owner: slurm
    group: slurm
    mode: "0644"
  notify:
    - Restart slurmctld
  tags:
    - slurm
    - slurm_configure

- name: Create node resume file
  ansible.builtin.copy:
    content: "{{ slurm_conf_resume_program}}"
    dest: "{{ slurm_conf_resume_program_path }}"
  when: slurm_conf_resume_program
  notify:
    - Restart slurmctld
  tags:
    - slurm
    - slurm_configure

- name: Create node suspend file
  ansible.builtin.copy:
    content: "{{ slurm_conf_suspend_program}}"
    dest: "{{ slurm_conf_suspend_program_path }}"
  when: slurm_conf_suspend_program
  notify:
    - Restart slurmctld
  tags:
    - slurm
    - slurm_configure

- name: Create slurmctld service file
  ansible.builtin.template:
    src: templates/slurmctld.service.j2
    dest: /etc/systemd/system/slurmctld.service
    owner: root
    group: root
    mode: "0644"
  tags:
    - slurm
    - slurm_install_controller

- name: Start slurmctld service
  ansible.builtin.service:
    name: slurmctld
    state: started
    enabled: true
  tags:
    - slurm
    - slurm_install_controller
