---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: rockylinux
    privileged: True
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/usr/sbin/init"
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
