---
# tasks file for datalake
- name: Install packages
  package:
    name: "{{item}}"
    state: present
  tags:
    - datalake
    - datalake_python
  loop:
    - python3-virtualenv

- name: Install postgresql local clients
  package:
    name: "{{item}}"
    state: present
  tags:
    - datalake
  loop:
    - python3-pip

- name: add deploy key to server
  copy:
    content: "{{datalake_github_private_key}}"
    dest: "/root/.ssh/id_ed25519"
    owner: "root"
    group: "root"
    mode: "0600"
  tags:
    - datalake

- name: Copy scripts down
  ansible.builtin.git:
    repo: git@github.com:dstdev/dst-automations.git
    key_file: /root/.ssh/id_ed25519
    accept_hostkey: yes
    dest: /opt/dst-automations
    force: yes
  tags:
    - datalake

- name: Install dst package in virtual environment
  pip:
    name: /opt/dst-automations
    #name: git+ssh://git@github.com/dstdev/dst-automations.git
    virtualenv: /opt/venv
  environment:
    GIT_SSH_COMMAND: "ssh -i /root/.ssh/id_ed25519"
  tags:
    - datalake
    - datalake_python

- name: Create environment file for automations
  template:
    src: templates/env.j2
    dest: /opt/dst-automations/.env
    owner: root
    group: root

  tags:
    - datalake

- name: Create cron jobs for all automations
  include_role:
    name: cronjob
  vars:
    cronjob_cron_name: "Automation script on {{ansible_hostname}} {{item.name}}"
    cronjob_description: "Cronjob for {{item.script}}"
    cronjob_job: "DST_ENV_FILE=/opt/dst-automations/.env /opt/venv/bin/python /opt/dst-automations/scripts/{{item.script}}" 
    cronjob_minute: '{{item.minute | default("*")}}'
    cronjob_hour: '{{item.hour | default("*")}}'
    cronjob_day: '{{item.day | default("*")}}'
    cronjob_month: '{{item.month | default("*")}}'
    cronjob_weekday: '{{item.weekday | default("*")}}'
    cronjob_tags:
      - automation
  loop: "{{datalake_cronjobs}}"
  tags:
    - datalake
