---
# tasks file for datalake
- name: Install packages
  package:
    name: "{{item}}"
    state: present
  tags:
    - datalake
    - datalake_python
  loop:
    - python3-virtualenv

- name: Install postgresql local clients
  package:
    name: "{{item}}"
    state: present
  tags:
    - datalake
  loop:
    - python3-pip

- name: add deploy key to server
  copy:
    content: "{{datalake_github_private_key}}"
    dest: "/root/.ssh/id_ed25519"
    owner: "root"
    group: "root"
    mode: "0600"
  tags:
    - datalake

- name: Install dst package in virtual environment
  pip:
    #name: file://opt/dst-automations
    name: git+ssh://git@github.com/dstdev/dst-automations.git
    virtualenv: /opt/venv
  environment:
    GIT_SSH_COMMAND: "ssh -i /root/.ssh/id_ed25519"
  tags:
    - datalake
    - datalake_python

