---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: centos:7
    privileged: true
    volume_mounts:
      - "sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: "/usr/sbin/init"
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
