
loki_config:
  auth_enabled: false
  server:
    http_listen_port: 3100
    grpc_listen_port: 9095
  storage_config:
    boltdb_shipper:
      active_index_directory: /var/lib/loki/index
      cache_location: /var/lib/loki/cache
      cache_ttl: 24h
      shared_store: filesystem
    filesystem:
      directory: /var/lib/loki/chunks
  ingester:
    lifecycler:
      address: 127.0.0.1
      ring:
        kvstore:
          store: inmemory
        replication_factor: 1
      final_sleep: 0s
    chunk_idle_period: 5m
    max_chunk_age: 1h
    chunk_retain_period: 30m
    max_transfer_retries: 0
  schema_config:
    configs:
      - from: 2022-01-01
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h
