- name: Install packages
  package:
    name: "{{item}}"
    state: present
  loop:
    - x2goserver
    - x2goserver-session

- name: Link startkde
  file:
    src: /usr/bin/startplasma-x11
    dest: /usr/bin/startkde
    owner: root
    group: root
    state: link
