name: Molecule
on:
  workflow_dispatch:
  push:
    paths:
      - cobbler
      - easybuild
      - moosefs-client
      - nhc
      - prometheus_blackbox_exporter
      - prometheus_dcgm_exporter
      - prometheus_gpfs_exporter
      - prometheus_infiniband_exporter
      - prometheus_node_exporter
      - prometheus_slurm_exporter
      - prometheus-server
      - slurm
      - spack
      - tmux
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        folder:
          - cobbler
          - easybuild
          - moosefs-client
          - nhc
          - prometheus_blackbox_exporter
          - prometheus_dcgm_exporter
          - prometheus_gpfs_exporter
          - prometheus_infiniband_exporter
          - prometheus_node_exporter
          - prometheus_slurm_exporter
          - prometheus-server
          - spack
          - tmux
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies.
        run: pip3 install yamllint ansible-lint ansible molecule 'molecule-plugins[docker]' docker

      - name: Install Galaxy dependencies.
        run: ansible-galaxy collection install community.docker

      - name: Run molecule
        run: "cd dstdev/ansible-roles/${{matrix.folder}} && molecule test"
