name: Molecule
on:
  workflow_dispatch:
  push:
    paths:
      - prometheus_node_exporter
      - prometheus_gpfs_exporter
      - prometheus_dcgm_exporter
      - prometheus_blackbox_exporter
      - prometheus_ibm_exporter
      - prometheus_slurm_exporter
      - prometheus_cgroup_exporter
      - virtualgl
      - turbovnc
      - slurm
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        folder:
          - prometheus_node_exporter
          - prometheus_gpfs_exporter
          - prometheus_dcgm_exporter
          - prometheus_blackbox_exporter
          - prometheus_ibm_exporter
          - prometheus_slurm_exporter
          - prometheus_cgroup_exporter
          - virtualgl
          - turbovnc
          - slurm
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies.
        run: pip3 install yamllint ansible-lint ansible "molecule[lint,docker]"

      - name: Install Galaxy dependencies.
        run: ansible-galaxy collection install community.docker

      - name: Run molecule
        run: "cd dstdev/ansible-roles/${{matrix.folder}} && molecule --debug test"
